# Support Python 3.10+.
target-version = "py310"
# Set the maximum line length to 130.
line-length = 130

[lint]
ignore = [
    "ANN101", # Allow missing type annotation for `self` in method
    "ANN102", # Allow missing type annotation for `cls` in classmethod
    "COM812", # Allow missing-trailing-comma
    "D203",   # Enable no-blank-line-before-class (D211)
    "D212",   # Enable multi-line-summary-second-line (D213)
    "PD",     # pandas-vet (false-positives)
    # TODO: Enable the following sets when possible
    "A",    # flake8-builtins
    "ANN",  # flake8-annotations
    "ARG",  # flake8-unused-arguments
    "B",    # flake8-bugbear
    "BLE",  # flake8-blind-except
    "C4",   # flake8-comprehensions
    "C90",  # mccabe
    "D",    # pydocstyle
    "DTZ",  # flake8-datetimez
    "EM",   # flake8-errmsg
    "ERA",  # eradicate
    "FBT",  # flake8-boolean-trap
    "FIX",  # flake8-fixme
    "INP",  # flake8-no-pep420
    "N",    # pep8-naming
    "PERF", # perflint
    "PGH",  # pygrep-hooks
    "PIE",  # flake8-pie
    "PL",   # pylint
    "PT",   # flake8-pytest-style
    "PTH",  # flake8-use-pathlib
    "PYI",  # flake8-pyi
    "RET",  # flake8-return
    "RUF",  # ruff
    "S",    # flake8-bandit
    "SIM",  # flake8-simplify
    "SLF",  # flake8-self
    "T20",  # flake8-print
    "TCH",  # flake8-type-checking
    "TD",   # flake8-todos
    "TID",  # flake8-tidy-imports
    "TRY",  # tryceratops
    "UP",   # pyupgrade
]
select = ["ALL"]
isort.known-first-party = ["abacura", "abacura_kallisti"]

[lint.per-file-ignores]
"**/tests/**/*.py" = [
    "S101",    # asserts allowed in tests...
    "FBT",     # don"t care about booleans as positional arguments in tests
    "INP001",  # no implicit namespace
    "D",       # don"t care about documentation in tests
    "S603",    # `subprocess` call: check for execution of untrusted input
    "PLR0912", # Too many branches
    "PLR2004", # Magic value used in comparison, consider replacing with a constant variable
]
